### ISSUE TITLE
Please Help - error installing greppo (Windows)

### ISSUE THREAD

**Issue by davidestrada1** [greppo-io/greppo#19]
Hello Guys!

Thanks for building Greppo! I am having some issues installing it, so I would really appreciate it if you could please five a hand:
![image](https://user-images.githubusercontent.com/57303993/157893504-04707327-af7e-4be7-a3db-466cc3a8c687.png)

I have created a different environment in Anaconda Prompt and tried to install greppo there, as @krishadi mentioned in the Discord group, but still with no success.

Any help would be greatly appreciated.

Looking forward to hearing from you soon. Have a good one!

David E.

**Comment by gtitov** [comment]
Installation of geoprocessing modules can be frustrating on Windows.

I would recommend to install GDAL and Shapely from the great [Unofficial Windows Binaries for Python Extension Packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/) before `pip install greppo`. You can follow [this tutorial](https://gist.github.com/gtitov/f4da8a535410dc3db25c5e384dfdcce6).

Not sure about Anaconda but it worked for me with venv.

**Comment by davidestrada1** [comment]
Thanks @gtitov , but I did it and still got the same error.

**Comment by krish-adi** [comment]
Hey @davidestrada1 ,

Could you check if the Python version you are using is >=3.9.4.

Inside your conda environment, install geopandas first using `cond install geopandas` and then install greppo using `pip install greppo`. 

Let me know if this works.
