### ISSUE TITLE
Installing greppo (dependencies)

### ISSUE THREAD

**Issue by grndng** [greppo-io/greppo#2]
The installation of [Fiona](https://github.com/Toblerity/Fiona) on Windows machines usually doesn't work by default. Since `Fiona` seems to be a dependency of `greppo` (and `GDAL` being a dependency of `Fiona`, ...) I'd give a hint regarding a manual installation with e.g. the [wheel files](https://www.lfd.uci.edu/~gohlke/pythonlibs/) by Christoph Gohlke.

It probably is up for discussion on whose repository this issue should be submitted and I understand if you think that it isn't the `greppo` repository since you are targeting Data Scientists that probably know their ways around Python and packages. However, in order to make the library available to a wider audience, I think the accessibility should be as best as possible which is why it might make sense to hint how to get the dependencies right.

**Comment by stangirala** [comment]
@grndng Thanks for flagging this! Just to be clear when you mean hint I'm guessing you mean a hint in the docs right?

**Comment by grndng** [comment]
@stangirala Sorry for being very late with my reaction. I definitely mean a hint in the documentation :)

**Comment by stangirala** [comment]
@grndng thanks! lmk if you use Greppo and run into other issues!

**Comment by krish-adi** [comment]
Added the hint to the Readme. Thanks @grndng :)
