### ISSUE TITLE
Server didn't  generate wms layer 

### ISSUE THREAD

**Issue by ngohailyodv** [greppo-io/greppo#21]
Hi,
I uploaded geojson file on ckan but server didn't generate wms layer.
![image](https://user-images.githubusercontent.com/60173863/158150110-4053aa9e-5180-4b53-b07a-3138dda2ca5c.png)

**Comment by krish-adi** [comment]
Could you give more context to the issue? And how I can reproduce it?

**Comment by ngohailyodv** [comment]
Hi,
I would the system generate wms layer when I upload geojson on ckan so that I can use terramaps for visualization

**Comment by krish-adi** [comment]
So if I understand you, CKAN is not generating the wms layer API, which you would like to use in Greppo? Then this is a CKAN problem.

**Comment by ngohailyodv** [comment]
Here is the dataset that I uploaded into ckan and the system generate db_table file and wms layer
https://data.vietnam.opendevelopmentmekong.net/dataset/mekong-regional-hydropower-dams-2020
![image](https://user-images.githubusercontent.com/60173863/158774646-ee52bdc0-3886-415b-aa03-8e83062e19c2.png)

**Comment by gtitov** [comment]
I don't think this is a right place for such questions. Better try https://gis.stackexchange.com/ next time.

Yet here is the working example

```python
from greppo import app

app.base_layer(
    name="CartoDB Light",
    visible=True,
    url="https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png",
    subdomains=None,
    attribution='&copy; <a target="_blank" href="http://osm.org/copyright">OpenStreetMap</a> contributors',
)

app.wms_tile_layer(
    url='https://data.opendevelopmentmekong.net/geoserver/ODMekong/7c0f8345-c8a8-4b61-824a-42b391d6097f/wms?', 
    name='Mekong_Hydro_Power_Dam_2020', 
    format='image/png', 
    layers='7c0f8345-c8a8-4b61-824a-42b391d6097f', 
    description='Mekong_Hydro_Power_Dam_2020'
)
```

You probably use the wrong url in `app.wms_tile_layer`. It can be useful to test wms connection in qgis and study wms capabilities response.
