### ISSUE TITLE
Error: 'GreppoApp' object has no attribute 'base_layer'

### ISSUE THREAD

**Issue by sotosoul** [greppo-io/greppo#26]
That's a great project and I'm very happy to try it out! Unfortunately, after installing the necessary dependencies and create a sample `app.py` with `app.base_layer( ... )` as shown in the demo section of the documentation, I keep getting errors like: 
`AttributeError: 'GreppoApp' object has no attribute 'base_layer'`. 

Is there something I'm missing?

**Comment by krish-adi** [comment]
Hey @sotosoul,

Are you running the `app.py` in the terminal as the following?

```shell
greppo serve app.py
```
