### ISSUE TITLE
"_" in the name of display causes errors

### ISSUE THREAD

**Issue by tahsbahs** [greppo-io/greppo#39]
Having an '_' character in the name of the display method causes errors. Suggestion is to raise an error that is more meaningful.

**Comment by fedderw** [comment]
Yeah, I just figured this out myself, but I had to search through the library. Is this a non-python constraint causing this?

**Comment by krish-adi** [comment]
Hey! 

Yeah, this is a non-python constraint. Greppo uses the name as an unique identifier to bind it with the API. 

The underscores are used for internal processing and can conflict with how this is done.
